#CREATE EXTERNAL TABLE WITH PARTITION

CREATE EXTERNAL TABLE IF NOT EXISTS bdc_5.cjk_mart_usr_hdfs (
	user_name		STRING,
	type			STRING,
	table_name		STRING,
	SIZE			INT)
PARTITIONED BY (etl_ym	STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION 'hdfs://ndap/user/b10144880/'