#CREATE EXTERNAL TABLE WITH PARTITION

CREATE EXTERNAL TABLE IF NOT EXISTS bdc_5.cjk_mart_usr_hdfs (
	user_name		STRING,
	type			STRING,
	table_name		STRING,
	SIZE			INT)
COMMENT 'User hdfs Usage'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
PARTITIONED BY (etl_ym)
LOCATION '/user/b10144880/hdfs_user'